export const ADD_WANTED_PLUGIN = 'ADD_WANTED_PLUGIN';
export const REMOVE_WANTED_PLUGIN = 'REMOVE_WANTED_PLUGIN';
export const ADD_OWNED_PLUGIN = 'ADD_OWNED_PLUGIN';
export const REMOVE_OWNED_PLUGIN = 'REMOVE_OWNED_PLUGIN';